---
roles:
  - src: https://github.com/christopherlouet/ansible-role-docker.git
    version: main
    name: clouet.docker
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 7.3.0
