---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: molecule-docker
    image: python:slim-bullseye
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy} "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - molecule
      - tock
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 1
    ANSIBLE_KEEP_REMOTE_FILES: 0
    ANSIBLE_ROLES_PATH: "../../roles:../../roles.internal"
    ANSIBLE_COLLECTIONS_PATH: "../../collections"
  inventory:
    links:
      group_vars: "../../group_vars"
      host_vars: "../../host_vars"
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer
      roles_path: "roles:roles.internal"
      collections_paths: "collections"
scenario:
  name: default
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  create_sequence:
    - dependency
    - create
    - prepare
  destroy_sequence:
    - destroy
verifier:
  name: ansible
