---

- name: Install packages using apt
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
    update_cache: false

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Verify that we have the key with the fingerprint
  ansible.builtin.apt_key:
    id: "{{ docker_debian_apt_key }}"
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: false

- name: Create docker group
  ansible.builtin.group:
    name: "{{ docker_group }}"
    state: present

- name: Add remote user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ docker_group }}"
    append: true

- name: Run and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Check current docker-compose version
  ansible.builtin.command: docker-compose --version
  register: check_docker_compose_version
  changed_when: false
  failed_when: false
  check_mode: false

- name: Get current docker-compose version
  ansible.builtin.set_fact:
    docker_compose_current_version: "{{ check_docker_compose_version.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
  when:
    - check_docker_compose_version.rc == 0

- name: Install or upgrade docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    force: true
  when: >
    docker_compose_current_version is not defined
    or docker_compose_current_version is version(docker_compose_version, '<')
