---
dependencies: []

galaxy_info:
  author: clouet
  description: This role will assume the install of docker and docker-compose.
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags: []
